name: NCTL Scan Pipeline Demo
run-name: ${{ github.actor }} has triggered Scan Action 🚀
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

env:
  NIRMATA_TOKEN: ${{secrets.NIRMATA_TOKEN}}
  NIRMATA_URL: ${{secrets.NIRMATA_URL}}

jobs:
  NCTL-Scan-Repository:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out main repository code
        uses: actions/checkout@v4

      - name: nctl-scan-installer
        uses: nirmata/action-install-nctl-scan@v0.0.6

      - name: test-install
        run: nctl scan repository --help

      - name: nctl login
        run: nctl login --url $NIRMATA_URL --token $NIRMATA_TOKEN --userid santanu.mukherjee@ltimindtree.com
        
      - name: NCTL Scan Repository
        run: nctl scan repository --policy-sets pss-baseline,pss-restricted,rbac-best-practices,dockerfile-best-practices,ecs-tf-config-best-practices,s3-tf-config-best-practices --publish-token $NIRMATA_TOKEN
  
      - run: echo "🍏 This job's status is ${{ job.status }}."
